---
title: "Split csv into individual csv based on column"
author: "Henry Lau"
date: "1 September 2017"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Split data for each LSOA

```{r}
PER <- read.csv("/Users/Lauh/Documents/Projects/Census Small Area Maps/affordabilitycalculator/activity.csv")
#View(PER)
for (name in levels(PER$LAD17CD)){
  #Subset the data by each MSOA, Area_code is the column name to split by
  tmp=subset(PER,LAD17CD==name)
  #Create a new filename for each MSOA - the folder 'cut' should already exist
  fn=paste('/Users/Lauh/Documents/Projects/Census Small Area Maps/affordabilitycalculator/data/Cut/',gsub(' ','',name),sep='','.csv')
  #Save the CSV file containing separate expenses data for each MP
  write.csv(tmp,fn,row.names=FALSE)
  }
```


Source: [Splitting a Large CSV File into Separate Smaller Files Based on Values Within a Specific Column](https://www.r-bloggers.com/splitting-a-large-csv-file-into-separate-smaller-files-based-on-values-within-a-specific-column/)